# Generated by Django 5.0.3 on 2024-03-06 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_dataframemodel_column_types_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataframemodel',
            name='dtypess',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dataframemodel',
            name='file_path',
            field=models.FilePathField(default=''),
        ),
    ]
