# Generated by Django 5.0.3 on 2024-03-07 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_dtypess_dataframemodel_dtypes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframemodel',
            name='file_path',
            field=models.FileField(upload_to='dataframes'),
        ),
    ]
