# Generated by Django 5.0.3 on 2024-03-07 00:17

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dataframemodel_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframemodel',
            name='file_path',
            field=models.FileField(upload_to=api.models.content_file_name),
        ),
    ]
