# Generated by Django 5.0.3 on 2024-03-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_dataframemodel_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframemodel',
            name='dtypes',
            field=models.JSONField(default=dict, null=True),
        ),
    ]
