# Generated by Django 5.0.3 on 2024-03-07 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_dataframemodel_dtypes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataframemodel',
            old_name='file_path',
            new_name='file',
        ),
    ]
