# Generated by Django 5.0.3 on 2024-03-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_file_path_dataframemodel_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframemodel',
            name='file',
            field=models.FileField(upload_to='content'),
        ),
    ]
